export const GAME_COPY = {
  TITLE: 'InkEcho',
  DESCRIBE_PHASE_TITLE: 'Describe What You See',
  DESCRIBE_PHASE_SUBTITLE: 'Write a creative sentence explaining the drawing or prompt.',
  DESCRIBE_INPUT_LABEL: 'Your Description',
  DESCRIBE_INPUT_PLACEHOLDER: 'E.g., An astronaut riding a rainbow dolphin through space...',
  DESCRIBE_SUBMIT_BUTTON: 'Submit Description',
  DRAW_PHASE_TITLE: 'Draw This Prompt',
  DRAW_PHASE_SUBTITLE: 'Use your canvas tools to illustrate what was described.',
  DRAW_PLACEHOLDER: 'Canvas Drawing is enabled in Milestone 5.',
  WAITING_TITLE: 'Waiting for Players',
  WAITING_SUBTITLE: 'is currently taking their turn. Sit tight!',
  PAUSED_TITLE: 'Game Paused',
  PAUSED_SUBTITLE: 'The host has paused the game. Timers are temporarily frozen.',
  RESUME_BUTTON: 'Resume Game',
  PAUSE_BUTTON: 'Pause Game',
  SPECTATING_BANNER: 'You are spectating this match.',
  RECONNECTING_BANNER: 'Reconnecting to game server...',
  TIME_RUNNING_OUT: 'Hurry up! Time is almost up!',
  ROUND_INDICATOR: 'Round',
  CHAIN_INDICATOR: 'Chain',
  TURN_INDICATOR: 'Turn',
} as const;
