export const GAME_CONFIG = {
  DEFAULT_DESCRIBE_TIMER_SEC: 60,
  DEFAULT_DRAW_TIMER_SEC: 90,
  MIN_TIMER_SEC: 30,
  MAX_TIMER_SEC: 180,
  MAX_DESCRIPTION_LENGTH: 200,
  REVEAL_STEP_DURATION_MS: 3000,
  DISCONNECT_GRACE_PERIOD_SEC: 30,
  MAX_CANVAS_EXPORT_SIZE_BYTES: 2 * 1024 * 1024, // 2MB
} as const;
