export const ROOM_CONFIG = {
  MIN_PLAYERS: 3,
  MAX_PLAYERS: 12,
  DEFAULT_MAX_PLAYERS: 8,
  DEFAULT_ROUNDS: 1,
  MAX_ROUNDS: 3,
  ROOM_CODE_LENGTH: 6,
  ROOM_CODE_ALPHABET: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
  DISPLAY_NAME_MIN_LENGTH: 2,
  DISPLAY_NAME_MAX_LENGTH: 20,
} as const;
